<footer>
    <div class="footer-body">
        <div class="footer-content">
            <h5>Quick Action</h5>
            <ul class="footer-ul">
                <li class="footer-li"><a href="index.php">Home</a></li>
                <li class="footer-li"><a href="jobs.php">Job Descriptions</a></li>
                <li class="footer-li"><a href="apply.php">Application</a></li>
                <li class="footer-li"><a href="about.php">About us</a></li>
                <li class="footer-li"><a href="enhancements.php">Enhancement</a></li>
            </ul>
        </div>
        <div class="footer-content">
            <h5>Members</h5>
            <ul class="footer-ul">
                <li class="footer-li"><a href="about.php#NNam">Nhat Nam</a></li>
                <li class="footer-li"><a href="about.php#BTung">Ba Tung</a></li>
                <li class="footer-li"><a href="about.php#TKhang">Thuan Khang</a></li>
                <li class="footer-li"><a href="about.php#NQuyen">Ngoc Quyen</a></li>
                <li class="footer-li"><a href="about.php#TAnh">Tuan Anh</a></li>
            </ul>
        </div>
    </div>
</footer>

<div class="footer-bottom">
    <p>
        Copyright &copy; 2023 All Right Reserved <br>
        Swinburne University of Technology - COS10026 - Computer Technology Inquiry Project
    </p>
</div>
