<nav class="navbarT">
    <a href="index.php" <?php if ($current_page == "index.php") { echo 'class="active"'; } ?>><i class=""></i> Home</a>
    <a href="jobs.php" <?php if ($current_page == "jobs.php") { echo 'class="active"'; } ?>><i class=""></i> Jobs</a>
    <a href="apply.php" <?php if ($current_page == "apply.php") { echo 'class="active"'; } ?>><i class=""></i> Apply</a>
    <a href="about.php" <?php if ($current_page == "about.php") { echo 'class="active"'; } ?>><i class=""></i> About</a>
    <a href="enhancements2.php" <?php if ($current_page == "enhancements2.php") { echo 'class="active"'; } ?>><i class=""></i> Enhancements</a>
    <a href="phpenhancements.php" <?php if ($current_page == "phpenhancements.php") { echo 'class="active"'; } ?>><i class=""></i> Management</a>
</nav>
